//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCSaveEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCSaveEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wake and bake 
        ///Making some dough 
        ///So baked right now 
        ///Fledgling bakery 
        ///Affluent bakery 
        ///World-famous bakery 
        ///Cosmic bakery 
        ///Galactic bakery 
        ///Universal bakery 
        ///Timeless bakery 
        ///Infinite bakery 
        ///Immortal bakery 
        ///Don&apos;t stop me now 
        ///You can stop now 
        ///Cookies all the way down 
        ///Overdose 
        ///Casual baking 
        ///Hardcore baking 
        ///Steady tasty stream 
        ///Cookie monster 
        ///Mass producer 
        ///Cookie vortex 
        ///Cookie pulsar 
        ///Cookie quasar 
        ///Oh hey, you&apos;re still here 
        ///Let&apos;s never bake again 
        ///Sacrifice 
        ///Oblivion         /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string achievements {
            get {
                return ResourceManager.GetString("achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ccbg {
            get {
                object obj = ResourceManager.GetObject("ccbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinforced index finger 
        ///Carpal tunnel prevention cream 
        ///Ambidextrous 
        ///Thousand fingers 
        ///Million fingers 
        ///Billion fingers 
        ///Trillion fingers 
        ///Forwards from grandma 
        ///Steel-plated rolling pins 
        ///Lubricated dentures 
        ///Cheap hoes 
        ///Fertilizer 
        ///Cookie trees 
        ///Sturdier conveyor belts 
        ///Child labor 
        ///Sweatshop 
        ///Sugar gas 
        ///Megadrill 
        ///Ultradrill 
        ///Vanilla nebulae 
        ///Wormholes 
        ///Frequent flyer 
        ///Antimony 
        ///Essence of dough 
        ///True chocolate 
        ///Ancient tablet 
        ///Insane oatling workers 
        ///Soul bond 
        ///Flux capacit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string upgrades {
            get {
                return ResourceManager.GetString("upgrades", resourceCulture);
            }
        }
    }
}
